nvpro-samples/vk_video_samples

vk_video_decoder/libs/NvVkDecoder/NvVkDecoder.cpp
should be VK_STD_VULKAN_VIDEO_CODEC_H265_DECODE_SPEC_VERSION instead of VK_STD_VULKAN_VIDEO_CODEC_H264_DECODE_SPEC_VERSION
=> NvVkVideoDecoder: fix typo if codec type is H265

common/include/VkVideoCore/VkVideoCoreProfile.h
Using `static_assert` without an error string is a C++17 extension (https://en.cppreference.com/w/cpp/language/static_assert)
Adding an empty string suppresses noisy warnings since this header gets included in many places. Alternatively, the assertions could be removed
```
[20/21] Building CXX object demos/vk-video-dec/CMakeFiles/vk-video-dec-test.dir/__/__/libs/VkVideoDecoder/VkVideoDecoder.cpp.o
In file included from /home/stephan/projects/vk_video_samples/vk_video_decoder/libs/VkVideoDecoder/VkVideoDecoder.cpp:21:
In file included from /home/stephan/projects/vk_video_samples/vk_video_decoder/../common/include/VkVideoCore/VulkanVideoCapabilities.h:24:
/home/stephan/projects/vk_video_samples/common/include/VkVideoCore/VkVideoCoreProfile.h:38:110: warning: 'static_assert' with no message …
```
=> chore: suppress warning about `static_assert`

common/libs/VkCodecUtils/VulkanVideoProcessor.cpp, vk_video_decoder/include/vkvideo_parser/PictureBufferBase.h
Fixes a warning that turns into an error on MSVCs.
Fixes an issue with waiting for fences when the first wait times out.
=> Fix windows build and correctly wait for the frame to finish decoding before outputting to file.

vk_video_decoder/demos/vk-video-dec/Main.cpp
If a compute queue isn't requested at InitPhysicalDevice() time, the queue family for compute won't be retrieved. Then if createComputeQueue is set in CreateVulkanDevice, vkGetDeviceQueue will be called with queueFamilyIndex = -1.
=> decoder: only create compute queue when requested

common/libs/VkCodecUtils/pattern.cpp
Appears to be missed in f289815. The memory should be mapped and unmapped by VulkanDeviceMemoryImpl.
Related to #41.
=> Fix double vkUnmap calls

common/libs/VkCodecUtils/ProgramConfig.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.cpp
This performs three changes to the decoder app CLI parsing
- put the arguments in a data structure to make them available for a `--help` command
- add some additional validation for CLI parameters (missing values, values that start with `-` since likely a mistake). Please let me know if the check for arguments not starting with `-` https://github.com/nvpro-samples/vk_video_samples/pull/62/commits/57e7addf8764ff917bb036288f7787118a89a317 adds too much code and should be omitted. Without it the actual parsing code is quite short https://github.com/nvpro-samples/vk_video_samples/pull/62/commits/be1317ca494d41ea3a8fa0061d2a7844aa406498. https://docs.rs/clap/latest/clap/ performs such a check which had prevented me often to run a program with unintended CLI flags
- Remove flags `noTick` as it …
=> Implement `--help` for decoder app CLI and additional CLI arg validation

common/libs/VkCodecUtils/Helpers.h, common/libs/VkCodecUtils/ProgramConfig.h, common/libs/VkCodecUtils/VkVideoFrameToFile.h, common/libs/VkCodecUtils/VulkanVideoProcessor.cpp, common/libs/VkCodecUtils/VulkanVideoProcessor.h, vk_video_decoder/demos/vk-video-dec/CMakeLists.txt, vk_video_decoder/demos/vk-video-dec/Main.cpp
Allows the sample app to produce CRCs per frame and for the entire file for decode. The following commandline parameters have been added:
--crc
--crcframe
--crcinit
--y4m
Fixed --c to actually accept a max frame count instead of silently accepting a bolean as an inteteger..
=> CRC support and Y4M support

common/libs/VkCodecUtils/VulkanVideoProcessor.cpp
CRC output was showing erratic frame numbers.
=> Fix frame numbering in the CRC output

vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp
As VK_VIDEO_CAPABILITY_SEPARATE_REFERENCE_IMAGES_BIT_KHR is optional
support, the DPB mode should fallback to layered dpb
if the implementation does not support separate dpb.
=> Encoder: fallback to layered if separate not present

vk_video_decoder/libs/VkVideoDecoder/VkVideoDecoder.cpp, vk_video_decoder/libs/VulkanVideoFrameBuffer/VulkanVideoFrameBuffer.cpp
My thought here is that the transfer operation doesn't have to be done in the distinct case (since its allocated as linear already), so only set `m_useTransferOperation = true` in the coincide mode. Then the `VkVideoFrameBuffer` needs to provide the decode output image views for `IMAGE_VIEW_TYPE_LINEAR`.
Without this change, outputting to a file on a DISTINCT DPB implementation would have caused a crash, since the copy operation would have been attempted with the `dstImage` being NULL.
This still relies on the assumption that a distinct output for decoder images supports linear tiling.
@zlatinski: I'm not sure if this is the proper fix, as I don't fully understand what the image specs and such are supposed to do.
=> decoder: Fix file output for DISTINCT DPB case

vk_video_encoder/demos/vk-video-enc/CMakeLists.txt
The HelpersDispatchTable.* are already generated by the encoder lib.
=> demos: do not generate twice the HelpersDispatchTable

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH264.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH265.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH265.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp
The default value for B Frame count is 3 but some
implementation does not support B Frames.
Set the value to the max B Frame count supported
by the implementation if it exceeds the value.
=> EncoderConfig: introduce GetMaxBFrameCount

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.h
In case user does not specify --numFrames, the gopFrameCount was zero and causing a crash.
If user does not specify the numFrames, the number of frames in the input file should be used.
=> EncoderConfig: add input file get frame count

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.h
To support driver which does not support B Frame,
GetMaxBFrameCount has been introduced in
https://github.com/nvpro-samples/vk_video_samples/pull/103 but AV1 was not supported yet.
=> EncoderConfigAV1: Fix GetMaxBFrameCount

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.h
GetMaxBFrameCount needs to be overriden in the case of AV1Config
=> EncoderConfigAV1: add missing override

vk_video_decoder/libs/NvVideoParser/src/NextStartCodeAVX2.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeAVX512.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeNEON.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeSSSE3.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeSVE.cpp
a potential out-of-bondary access when the next start code isn't found in a SVE - for datasize < 2, for others - when the loop ends without finding the code and i == datasize (next iteration outside loop)
=> Fixed potential rare corner cases

vk_video_decoder/libs/NvVideoParser/src/NextStartCodeAVX2.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeAVX512.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeNEON.cpp, vk_video_decoder/libs/NvVideoParser/src/NextStartCodeSSSE3.cpp
The checks are redundant because the maximum possible value after the loop ends is `datasizeN - N`, loop step is `N` (I introduced them in a previous commit). Only the SVE-based code's change from the previous commit is required (left it)
=> Revert unneeded check

vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderAV1.cpp
For higher image resolutions and bitrates, the fixed 2MB buffer size is inadequate. To handle the worst-case scenario, ensure the bitstream size is the same as the input image size.
=> Set the bitstream buffer size to match the input image size.

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderAV1.cpp
Include compressed rate and different tiers to validate level support.
Update the sequence header with level and tier parameters with supported values.
=> AV1 profile and tier selection fix.

vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH265.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderStateAV1.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderStateH264.h
VUID-vkCmdEncodeVideoKHR-None-08318(ERROR / SPEC): msgNum: 1..1 - Validation Error: [ VUID-vkCmdEncodeVideoKHR-None-08318 ] Object 0: handle = 0x..1, type = VK_OBJECT_TYPE_VIDEO_SESSION_KHR; Object 1: handle = 0x..5, type = VK_OBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHR; | MessageID = 0x..9 | vkCmdEncodeVideoKHR(): The currently configured encode quality level (4) for VkVideoSessionKHR 0x..1[] does not match the encode quality level (0) VkVideoSessionParametersKHR 0x..5[] was created with.
"Video session parameters objects created with an encode operation are always created with respect to a video encode quality level. By default, the created video session parameters objects are created with quality level zero, unless otherwise specified by including a structure in the pCreateInfo->pNext …
=> Fixed quality level validation layer warning

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp
This change introduces a --repeatInputFrames option to allow for the file sequence to be repeated for the output compressed stream. When the input file sequence reaches the end, it gets restarted and repeated again until the numFrames is reached.
Also, implement the --startFrame option.
=> encode: add repeatInputFrames option

common/include/VkVideoCore/VulkanVideoCapabilities.h, common/libs/VkCodecUtils/VulkanDeviceContext.cpp, common/libs/VkCodecUtils/VulkanVideoSession.cpp, common/libs/VkCodecUtils/VulkanVideoSession.h, vk_video_decoder/libs/VkVideoDecoder/VkVideoDecoder.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigAV1.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH264.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH265.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfigH265.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbAV1.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH264.h, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH265.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH265.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderAV1.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH264.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH265.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH265.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoGopStructure.cpp, vk_video_encoder/libs/VkVideoEncoder/VkVideoGopStructure.h
This set of changes adds support in the encoder sample application for the [VK_KHR_video_encode_intra_refresh](https://registry.khronos.org/vulkan/specs/latest/man/html/VK_KHR_video_encode_intra_refresh.html) extension.
=> Add intra refresh support

vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.h
Set automatically the input.msbShift value to the default shift, if not explicitly set by the API for 10/12-bit input.
=> encode: Set the MSB shift for 10/12-bit input

vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH264.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderDpbH264.h, vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoderH264.cpp
Populating reference slot details for encode after DPB management and picture marking sometime result into incorrect details.   This includes incorrect picture, poc and other values related to the reference picture.  So, populate all the details before DPB management.
=> Update DPB after populating reference slot infos

common/libs/VkCodecUtils/VulkanFrame.cpp, vk_video_encoder/demos/vk-video-enc/Main.cpp, vk_video_encoder/libs/VkVideoEncoder/VkEncoderConfig.cpp
DEBUG ONLY: Encoder input debug display support
Use the --enableDebugEncoderInputDisplay option
to present the encoder's input frames to the screen,
after the staging and compute filter and before the
encoder.
=> Encoder debug display support
